---
language: node_js
node_js:
  - "4"
  - "6"
  - "stable"

sudo: false

cache:
  directories:
    - node_modules
    - tests/fixtures/app-simple/node_modules

before_install:
  - npm config set spin false

install:
  - npm install
  - cd tests/fixtures/app-simple && npm install && cd -

script:
  - npm test
